application: gaels
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /templates
  static_dir: templates
  application_readable: true

- url: /resources
  static_dir: resources
  
- url: /start-page
  script: handlers.main.app

- url: /favicon\.ico
  static_files: resources/favicon.ico
  upload: favicon\.ico

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
