#!/usr/bin/env python

import webapp2
import jinja2
import os

import model.user as user_info_model
import model.key as key_model
import model.appinfo as AppInfo

from google.appengine.api import users

# Defines path to templates
templates_path = os.path.join(os.path.dirname(__file__),'..','templates')

# Defines de Jinja environment
JINJA_ENVIRONMENT = jinja2.Environment(
    loader=jinja2.FileSystemLoader(templates_path),
    extensions=['jinja2.ext.autoescape'],
    autoescape=True)


class KeyHandler(webapp2.RequestHandler):
	def get(self):
		# User data
		user = users.get_current_user()
		user_info = user_info_model.retrieve(user)


		# Key data
		all_keys = key_model.retrieve_all_keys()

		access_link = users.create_login_url("/")
		user_logged = False;
		template = JINJA_ENVIRONMENT.get_template("keys.html")

		# If the user is logged
		if user_info:
			user_logged = True;
			access_link = users.create_logout_url("/")

		template_values = {
			'user_logged': user_logged,
			'keylist': all_keys,
			'usr_info': user_info,
			'info': AppInfo,
			'access_link': access_link,
		}

		self.response.write(template.render(template_values))


class KeyInfoHandler(webapp2.RequestHandler):
	def get(self, keyname):
		# User data
		user = users.get_current_user()
		user_info = user_info_model.retrieve(user)

		# Key data
		unique_key = key_model.retrieve_key(keyname)

		access_link = users.create_login_url("/")
		template = JINJA_ENVIRONMENT.get_template("info-key.html")

		# If the user is logged
		if user_info:
			access_link = users.create_logout_url("/")

		template_values = {
			'key': unique_key,
			'usr_info': user_info,
			'info': AppInfo,
			'access_link': access_link,
		}

		self.response.write(template.render(template_values))


class MapKeyHandler(webapp2.RequestHandler):
	def get(self, keymap):
		# User data
		user = users.get_current_user()
		user_info = user_info_model.retrieve(user)

		# Key data
		keys_by_map = key_model.retrieve_all_keys_by_map(keymap)

		access_link = users.create_login_url("/")
		template = JINJA_ENVIRONMENT.get_template("map-key.html")

		# If the user is logged
		if user_info:
			access_link = users.create_logout_url("/")

		template_values = {
			'keylist': keys_by_map,
			'usr_info': user_info,
			'info': AppInfo,
			'access_link': access_link,
		}

		self.response.write(template.render(template_values))


def createKeys():
	key_model.insert(key_model.create("TerraGroup Labs access keycard",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f3x2f35x2fZkx78x78gmx78uav_Rghy_giikyy_qkeigx78j_oiut.vtmx3fbkx78youtx3dkhg1g25g12g0kj95il78hkg7k1kj846jx26o76i.sgx78qx3dosgmk_$/$/$/$/$","LABS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Lab. Black keycard",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2fgx2fg5x2fRqKG_Oiut.vtmx3fbkx78youtx3dkk87ghhl4jgjl650062lj6i28jk551gjx26o76i.sgx78qx3dosgmk_$/$/$/$/$","LABS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Lab. Blue keycard",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2fkx2fkkx2fRgh._qke._Znk_wagx78gtzotk_futk_oiut.vtmx3fbkx78youtx3d9i87j522ki7l78l68l7317g491ll0g77x26o76i.sgx78qx3dosgmk_$/$/$/$/$","LABS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Lab. Green keycard",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f0x2f0lx2fRgh_Qke_Hruiq8.vtmx3fbkx78youtx3d9544276084j0k9j29ij5ih7205lgg8igx26o76i.sgx78qx3dosgmk_$/$/$/$/$","LABS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Lab. Red keycard",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2flx2fl9x2fRgh._qke._Ykiax78oze_gx78yktgr.vtmx3fbkx78youtx3dk3k891i8l14kg6582li2i08711jk6giix26o76i.sgx78qx3dosgmk_$/$/$/$/$","LABS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Lab. Violet keycard",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2fgx2fg2x2fRgh._qke._Ykiax78oze_vuyz_oiut.vtmx3fbkx78youtx3dh52hi5lj8741h8l7h5h249518k1g83j5x26o76i.sgx78qx3dosgmk_$/$/$/$/$","LABS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Lab. Yellow keycard",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2fkx2fkhx2fRgh._qke._Grgx78s_yeyzks_iutzx78ur_vgtkr_oiut.vtmx3fbkx78youtx3dh5j13j743lji289907l7g5jh1k66i315x26o76i.sgx78qx3dosgmk_$/$/$/$/$","LABS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Lab. key. Arsenal storage room",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f8x2f8gx2fRgh_qke_Gx78yktgr_yzux78gmk_x78uus_oiut.vtmx3fbkx78youtx3d6608704lj67005h2k58664l7283gk5lix26o76i.sgx78qx3dosgmk_$/$/$/$/$","LABS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Lab. key. Manager office",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f6x2f63x2fRgh._qke._Sgtgmkx78_ulloik_oiut.vtmx3fbkx78youtx3d05gj35kk4i9hl5h50496320k6l934jl8x26o76i.sgx78qx3dosgmk_$/$/$/$/$","LABS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Lab. key. Testing area (weap.)",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2flx2flix2fRgh._qke._Zkyzotm_gx78kg_x2584ckgv.x2585_Oiut.vtmx3fbkx78youtx3d84jhhj62l398h690jk1526335450387kx26o76i.sgx78qx3dosgmk_$/$/$/$/$","LABS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Factory Key",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f8x2f89x2fLgizux78e_qke_oiut.vtmx3fbkx78youtx3dj980j3359502l526jikhjg5l1jg3013jx26o76i.sgx78qx3dosgmk_$/$/$/$/$", "FACTORY", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Key (pumping station)",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f3x2f33x2fJuux78_qke_Oiut.vtmx3fbkx78youtx3d7gg823kl3k2103l0201h0717j2i3ll47x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "FACTORY", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Key (admin)",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f3x2f33x2fJuux78_qke_Oiut.vtmx3fbkx78youtx3d7gg823kl3k2103l0201h0717j2i3ll47x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "FACTORY", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("ZB-014",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f1x2f1ix2fFH-670-qke-Oiut.vtmx3fbkx78youtx3d0351983ll5hgh7l94l26i732k6ij35hkx26o76i.sgx78qx3dosgmk_$/$/$/$/$", "WOODS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Yotota",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2flx2fl0x2fEuzuzg-igx78-qke-Oiut.vtmx3fbkx78youtx3di7487g64g7h463j0k804i92ig83h5llgx26o76i.sgx78qx3dosgmk_$/$/$/$/$", "WOODS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Customs Key",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2flx2fl5x2fIayzusy-ulloik-qke-Oiut.vtmx3fbkx78youtx3d496k813h2ljhg698548kjj716h853g3gx26o76i.sgx78qx3dosgmk_$/$/$/$/$", "CUSTOMS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Cabinet Key",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f9x2f90x2fIghotkz_qke_Mgy_Yzgzout_Oiut.vtmx3fbkx78youtx3d5l784h64856g70l579i129kl3g4h84kkx26o76i.sgx78qx3dosgmk_$/$/$/$/$", "CUSTOMS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Key (black handle)",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f6x2f66x2fIghotkz-qke-Oiut.vtmx3fbkx78youtx3d33g59i25097hi64j1g5l8lk22356gh98x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "CUSTOMS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Key (black handle: portable cabin key)",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f6x2f66x2fIghotkz-qke-Oiut.vtmx3fbkx78youtx3d33g59i25097hi64j1g5l8lk22356gh98x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "CUSTOMS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Unknown Key",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2flx2fl5x2fAtqtuct-qke-Oiut.vtmx3fbkx78youtx3dh29ig3i68jk6jik962gl8j49ll047j05x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "CUSTOMS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Cabin Key",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2fix2fi7x2fVux78zghrk-ighot-qke-Oiut.vtmx3fbkx78youtx3d3hg3h273g7j45k756110j45iig862i69x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "CUSTOMS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Checkpoint Key",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f5x2f51x2fInkiqvuotz_Qke_oiut.vtmx3fbkx78youtx3dk9k1i5625jj34770ill769h11jjh96i3x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "CUSTOMS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Machinery Key",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2fjx2fj4x2fSginotkx78e-qke-Oiut.vtmx3fbkx78youtx3d9102g7g4l83k8ilj70ihi8482h54i401x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "CUSTOMS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Cabin Key (trailer park)",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2fix2fi7x2fVux78zghrk-ighot-qke-Oiut.vtmx3fbkx78youtx3d3hg3h273g7j45k756110j45iig862i69x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "CUSTOMS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Dorm Guard Desk key",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2fkx2fk0x2fMJkyq-Qke-Oiut.vtmx3fbkx78youtx3d0gg1k38j3kl4986h74gj16397j1hii85x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "CUSTOMS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Room 104",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f4x2f4ix2fQke-760-Oiut.vtmx3fbkx78youtx3dl4ljkg9j733glgj785g97k8j7717j5h6x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "CUSTOMS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Room 105",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f1x2f12x2fQke-761-Oiut.vtmx3fbkx78youtx3d773g5580h10483g0l90133hlk1i262h2x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "CUSTOMS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Room 206",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f1x2f1kx2fQke-862-Oiut.vtmx3fbkx78youtx3dl464g3g42l5i3h0j6lh264hl4i1j9ihlx26o76i.sgx78qx3dosgmk_$/$/$/$/$", "CUSTOMS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Room 110",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f6x2f67x2fQke-776-Oiut.vtmx3fbkx78youtx3d9k7k2j86l32ik27h89hj5835h39ih525x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "CUSTOMS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Room 114",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f0x2f0hx2fQke-770-Oiut.vtmx3fbkx78youtx3d6l5831jh516l54jigg1k3753ji03l404x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "CUSTOMS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Room 108",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2fjx2fj3x2fQke-764-Oiut.vtmx3fbkx78youtx3dhhh4i74h820757j9il725h92115j383ix26o76i.sgx78qx3dosgmk_$/$/$/$/$", "CUSTOMS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Room 103",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f3x2f3kx2fJux78s_769_oiut.vtmx3fbkx78youtx3dg31520j71l8964g90il3jg75ghh01j6kx26o76i.sgx78qx3dosgmk_$/$/$/$/$", "CUSTOMS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Room 118",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2fhx2fh6x2fJux78s_774_oiut.vtmx3fbkx78youtx3d20ij167j0hi77886kg1g9ki90j7ki8ghx26o76i.sgx78qx3dosgmk_$/$/$/$/$", "CUSTOMS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Room 203",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2fix2fihx2fQke-869-Oiut.vtmx3fbkx78youtx3d8l0345lljl7ji95gk547j206782gl90lx26o76i.sgx78qx3dosgmk_$/$/$/$/$", "CUSTOMS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Room 204",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2flx2flkx2fQke-860-Oiut.vtmx3fbkx78youtx3d5k089h969i05ilhj6i07439g2ghg847jx26o76i.sgx78qx3dosgmk_$/$/$/$/$", "CUSTOMS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Room 214",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f9x2f92x2fQke-870-Oiut.vtmx3fbkx78youtx3d7lk10i34k17li389kh17j5gj9855666hx26o76i.sgx78qx3dosgmk_$/$/$/$/$", "CUSTOMS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Room 218",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f0x2f06x2fQke-874-Oiut.vtmx3fbkx78youtx3d79gh6g9g846h8jl39074h18i887g7874x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "CUSTOMS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Room 220",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f5x2f5gx2fQke-886-Oiut.vtmx3fbkx78youtx3d81201g4868jkl3gg50h8kl11i219514hx26o76i.sgx78qx3dosgmk_$/$/$/$/$", "CUSTOMS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Room 303",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f1x2f18x2fQke-969-Oiut.vtmx3fbkx78youtx3dilk767781g8ig94jg0562570il0554i1x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "CUSTOMS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Room 306",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f7x2f74x2fQke-962.vtmx3fbkx78youtx3d4j65h21k27jj47l95292g7ij45h820k3x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "CUSTOMS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Room 308",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2flx2flkx2fQke-964-Oiut.vtmx3fbkx78youtx3d418lj59gj543392ih8hi29910261i88lx26o76i.sgx78qx3dosgmk_$/$/$/$/$", "CUSTOMS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Marked Room (314)",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2fhx2fh7x2fSgx78qkj-qke-Oiut.vtmx3fbkx78youtx3d1i4g132k88049g1g46hj927275ii50g6x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "CUSTOMS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Room 315",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f2x2f2kx2fQke-971-Oiut.vtmx3fbkx78youtx3d089k46h16ijg2578ik91j0l58j829310x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "CUSTOMS", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Cottage Back Entrance Key",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f3x2f3jx2fIuzzgmk_Ynux78krotk_qke.vtmx3fbkx78youtx3d42lj45313g05i229jj5g02g63hl60j6lx26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Cottage Safe Key",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f6x2f62x2fIuzzgmkyglk.vtmx3fbkx78youtx3d7ll03k9395hk4k40i6l7g9469g66i786x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("SMW Car Key",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f8x2f8hx2fYSC_ynux78krotk_qke.vtmx3fbkx78youtx3dl50k4h1220i4h447392k198l360hhggix26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Sanatorium Key",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2fgx2fg3x2fVx78ksoykyUlYgtgzux78oasQke.vtmx3fbkx78youtx3dj4i86915g87g43l0ghlg72k4033kj455x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Shoreline Utility KeyHealth Resort",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2fhx2fh3x2fYzux78kx78uusQke.vtmx3fbkx78youtx3d6h780i546hi3687551j3i53l562j3088x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Health Resort Management Office Safe Key",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f6x2f62x2fIuzzgmkyglk.vtmx3fbkx78youtx3d7ll03k9395hk4k40i6l7g9469g66i786x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Health Resort Warehouse Safe Key",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f6x2f62x2fIuzzgmkyglk.vtmx3fbkx78youtx3d7ll03k9395hk4k40i6l7g9469g66i786x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Office 104 West Wing",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2fkx2fk9x2fYgt760.vtmx3fbkx78youtx3dj79441879l794g0k0g76ii044j1jl3i8x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Office 112 West Wing",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2fgx2fg7x2fYgt778oiut.vtmx3fbkx78youtx3d47208l7k38kk43hjggl1h7j529g6l743x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("West Wing 203",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2fjx2fj8x2fYgt869oiut.vtmx3fbkx78youtx3d68klg4hjlkig8h7gj9kl210h8h21j630x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("West Wing 205",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f8x2f89x2fYgt.861.vtmx3fbkx78youtx3d1k90716ik4g4jj5jh56h71958485j87ix26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("West Wing 207",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2fix2fikx2fYgt863oiut.vtmx3fbkx78youtx3d22iji9j82k35l8522492jhj04946hh05x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("West Wing 216",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f7x2f73x2fCkyz_872_Xkyux78z-Oiut.vtmx3fbkx78youtx3d70lj7jg6kj3j544jg37l09i565j138hhx26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("West Wing 218",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f8x2f8hx2fYgt.874.vtmx3fbkx78youtx3dk5j007ji6267j80747li100j8h63h5gix26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("West Wing 221",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2fix2fi4x2fYgt.887.vtmx3fbkx78youtx3dl601hg2l0hlii8555770hj78jkk94014x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("West Wing 222",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2flx2fl2x2fKgyz_888_Xkyux78z-Oiut.vtmx3fbkx78youtx3d515h79ijlg12gl565969i2159647i7k6x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("West Wing 219",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2fjx2fj4x2fYgt.875.vtmx3fbkx78youtx3d204i4i738i463gj680i711ig51383520x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("West Wing 220",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f9x2f9hx2fCkyz_886_Xkyux78z-Oiut.vtmx3fbkx78youtx3dk727lh7i4858gk1376g0k614gk21325ix26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("West Wing 301",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f4x2f43x2fCkyz_967_Xkyux78z-Oiut.vtmx3fbkx78youtx3di09il7h08h59898g58j9j03945459947x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("West Wing 303",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f5x2f53x2fYgt969Qke.vtmx3fbkx78youtx3d6537k589gl3hh2h0ihijl2l6k60h1656x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("West Wing 306",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f3x2f37x2fCkyzCotm962QkeOiut.vtmx3fbkx78youtx3d3251h1i77g7gi97i60118l770j9g9543x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("West Wing 309",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f1x2f15x2fYgt965oiut.vtmx3fbkx78youtx3d97j8l4h1l4gg7036gj40l1hkh819j142x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("321 Safe Key",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f5x2f57x2fYglk_987_qke.vtmx3fbkx78youtx3dg6k2k474lglk3l2ji5l490li49471k60x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("West Wing 323",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2fjx2fj0x2fYgt989oiut.vtmx3fbkx78youtx3d33k83g0460j358862lj392836336328hx26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Office 107 East Wing",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f7x2f77x2fKgyz_763_Xkyux78z-Oiut.vtmx3fbkx78youtx3d2h18j529gi710j787i562k954jj8l533x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Office 108 East Wing",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f3x2f32x2fYgt764QkeOiut.vtmx3fbkx78youtx3d377492hg14iji9j05j69l5293lkgj78gx26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("East Wing 206",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f3x2f33x2fYgt.862.vtmx3fbkx78youtx3dggj5i811l0319g85j40609429g53j95ix26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("East Wing 205",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f4x2f45x2fYgt861Kgyz.vtmx3fbkx78youtx3dkh267995457l7997kjk9l8g6017i3917x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("East Wing 209",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2fgx2fg2x2fYgt.865.vtmx3fbkx78youtx3d5gi7j61hgjlk5i0720li0lgj35k85j68x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("East Wing 213",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2flx2fljx2fYgt879.vtmx3fbkx78youtx3d3gk6g85649ig409612lg4j3gi7j9l3k1x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("East Wing 216",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f7x2f7ix2fYgt872kgyz.vtmx3fbkx78youtx3dh925095j3ik1916jgl981ig9klh880kix26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("East Wing 222",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f0x2f0gx2fYgt888Kgyz.vtmx3fbkx78youtx3d16534h6l4lj990258l58jgij3g0kj1ikx26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("East Wing 226",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f3x2f3lx2fYgt882oiut.vtmx3fbkx78youtx3d34kl43ihli7ii5196kh3jk1ik8i94li8x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("East Wing 306",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f3x2f31x2fYgt962Kgyz.vtmx3fbkx78youtx3di60i44gi17j1201g318l303l7g98k2llx26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("East Wing 308",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2fhx2fh5x2f964_Kgyz_Oiut.vtmx3fbkx78youtx3d012920jl358h9jjklh6ll48950108l59x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("East Wing 310",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f8x2f85x2fYgt.976.vtmx3fbkx78youtx3d009hgjh31j540g5l024023h05i334j05x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("East Wing 313",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2fix2fi2x2fYgt979oiut.vtmx3fbkx78youtx3d73l737386k4j859h9k0j04i00i208126x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("East Wing 314",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2fhx2fh9x2fKgyz_970_Xkyux78z-Oiut.vtmx3fbkx78youtx3d84h9k146h2k4h0495j8h1k408550ll34x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("East Wing 316",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2fkx2fkjx2f972_Kgyz_Oiut.vtmx3fbkx78youtx3dg2glg3l7g04354kg5k1lk32k04h02464x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("East Wing 322",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f7x2f74x2fYgt988oiut.vtmx3fbkx78youtx3d79759l810kkl5h724l30g80921hjl65lx26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("East Wing 328",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f0x2f0lx2f984_Kgyz_Oiut.vtmx3fbkx78youtx3d21l9j4j0k2j05ih073h9715k733llg7kx26o76i.sgx78qx3dosgmk_$/$/$/$/$", "SHORELINE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Goshan Register Key",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f9x2f9ix2fMuyngt_qke.vtmx3fbkx78youtx3d389587k55jlg79hklk72gi5i2lj4837kx26o76i.sgx78qx3dosgmk_$/$/$/$/$", "INTERCHANGE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("IDEA Register Key",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2fjx2fjkx2fOJKGXkmoyzkx78Qke.vtmx3fbkx78youtx3dh1j582392j34ij475g6h0j883g304ji3x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "INTERCHANGE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("OLI Register Key",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f6x2f6ix2fURO_igyn_x78kmoyzkx78.vtmx3fbkx78youtx3d2453i096425ji173jk61jili8i7h240kx26o76i.sgx78qx3dosgmk_$/$/$/$/$", "INTERCHANGE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("OLI Logistics Key",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2flx2fl7x2fRumUlloikQke.vtmx3fbkx78youtx3d0610gj309j23777ij3j256g2i8i4ig9hx26o76i.sgx78qx3dosgmk_$/$/$/$/$", "INTERCHANGE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("OLI Admin Office Key",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2flx2fl7x2fRumUlloikQke.vtmx3fbkx78youtx3d0610gj309j23777ij3j256g2i8i4ig9hx26o76i.sgx78qx3dosgmk_$/$/$/$/$", "INTERCHANGE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("OLI Utility Room Key",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f5x2f5gx2fUROAzoQke.vtmx3fbkx78youtx3d4g4g1ijk4gh3i2k2285462k5h4i1931lx26o76i.sgx78qx3dosgmk_$/$/$/$/$", "INTERCHANGE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Pharmacy Key",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f7x2f71x2fVngx78sgieQkeOiut.vtmx3fbkx78youtx3djgl3hi5g1g9ii6g91hj6583375h9709gx26o76i.sgx78qx3dosgmk_$/$/$/$/$", "INTERCHANGE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Emercom Medical Key",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2fix2fi5x2fKSKXIUS_Qke_oiutk.vtmx3fbkx78youtx3dlik7325j5hl0i2g34j73hj71k41j140gx26o76i.sgx78qx3dosgmk_$/$/$/$/$", "INTERCHANGE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Substation Utility Key",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f8x2f83x2fVuckx78_azoroze_Qke_oiutk.vtmx3fbkx78youtx3d8kg2hk21l6097ij2g0j76gkhhlhk1514x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "INTERCHANGE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("KIBA Key",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2fkx2fkix2fQohgQkeOiut.vtmx3fbkx78youtx3d103i332gl89j3h8i7k505il9gg292g7kx26o76i.sgx78qx3dosgmk_$/$/$/$/$", "INTERCHANGE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("KIBA Key 2",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f1x2f1gx2fQohgQke8Oiut.vtmx3fbkx78youtx3d27k15k21j0l4i45h43014kjl10h92k07x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "INTERCHANGE", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Weapons Safe Key",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f5x2f57x2fYglk_987_qke.vtmx3fbkx78youtx3dg6k2k474lglk3l2ji5l490li49471k60x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "UNKNOWN", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("(VAZ) Sixpack Key",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2fjx2fjjx2fYodvgiq-Qke-Oiut.vtmx3fbkx78youtx3dk0j25790413203lkk82j946191028hk3x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "UNKNOWN", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))
	key_model.insert(key_model.create("Weather Station Safe Key",\
		"https://c-3sux78kvnkay76x24mgskvkjogx2eiax78ykijtx2eius.g00.gamepedia.com/g00/3_c-3kyigvklx78uszgx78qub.mgskvkjog.ius_/c-3SUXKVNKAY76x24nzzvyx3ax2fx2fmgskvkjog.iax78ykijt.iusx2fkyigvklx78uszgx78qub_mgskvkjogx2f6x2f62x2fIuzzgmkyglk.vtmx3fbkx78youtx3d7ll03k9395hk4k40i6l7g9469g66i786x26o76i.sgx78qx3dosgmk_$/$/$/$/$", "UNKNOWN", "This should never leave your gamma and opens two additional extracts and allows you to open the locked room in third floor offices. Possible weapon spawn in locked room, two coats, loose loot and occasional high end ammo. This key spawns in the office of 3-Storey in Customs, the glass warehouse in Customs (in the blue locker), or very rarely behind the old gas station (under the tree near the medbag). All spawns marked here in bright blue. "))


def handle_404(request, response, exception):
    response.write('Oops! I could swear this page was here!')
    response.set_status(404)


def handle_500(request, response, exception):
    response.write('A server error occurred!')
    response.set_status(500)


app = webapp2.WSGIApplication([
	webapp2.Route(r'/keys', handler=KeyHandler, name='keys'),
	webapp2.Route(r'/keys/e/<keyname>', handler=KeyInfoHandler, name='keyinfo'),
	webapp2.Route(r'/keys/m/<keymap>', handler=MapKeyHandler, name='mapkeys'),
], debug=True)

# app.error_handlers[404] = handle_404
# app.error_handlers[500] = handle_500